spring.application.name=demoAI

spring.ai.openai.api-key=${GROQ_KEY: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}

spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.options.temperature=0.7

server.port = 8084